type Inputs = {
    nombre: string;
    descripcion: string;
    comprobante: string;
    fecha?: string;
    debe: string;
    haber: string;
    clienteId?: number;
    proveedoreId?: number;
    pagoDate?: string;
    depositoDate?: string;
    monto: string;
    destinatarioId?: number;
    destinatario?: string;
    libradoreId?: number;
    librador?: string;
    emisionDate?: string;
    salidaDate?: string;
    bancoId?: number;
    banco?: string;
    numero: string;
    titular?: string;
    cuit?: string;
    observaciones: string;
    estado: string;
};
